### ISSUE TITLE
how to install this library to my ide

### ISSUE THREAD

**Issue by luxta** [mahowik/BalancingWii#5]
am trying to buid this robot how do install this libray plz help.my name is christo from south africa.email christofaraz(at)gmail(dot)com

**Comment by MXZTY** [comment]
Hey Christo,
If you are using Arduino IDE,this is how i was able to do it: 
1) Download the repository as a zip folder, then extract it.
2) open the folder you just extracted the zip folder to, and double click the BalancingWii.ino file and it should automatically open everything needed in the arduino IDE. 
3) You can then verify the files by clicking the checkmark in the IDE in the top left corner, and check to make sure there are no errors displayed in the console at the bottom of the IDE.
4) You can then upload it to your arduino by clicking the arrow next to the check mark. 

If you get an error about the naming of the parent folder when trying to open the .ino file, just change the folder name to BalancingWii instead of BalancingWii-master. 

Much thanks to mahowik for providing this repository!

**Comment by mahowik** [comment]
Thanks for the comment. But for some reasom I don't see it on git...

**Comment by luxta** [comment]
ok many thanks mr mahowik i got that right,am now struggling with hc-05
module

**Comment by mahowik** [comment]
>> from MXZTY

Hey Christo,
If you are using Arduino IDE,this is how i was able to do it:

Download the repository as a zip folder, then extract it.
open the folder you just extracted the zip folder to, and double click the BalancingWii.ino file and it should automatically open everything needed in the arduino IDE.
You can then verify the files by clicking the checkmark in the IDE in the top left corner, and check to make sure there are no errors displayed in the console at the bottom of the IDE.
You can then upload it to your arduino by clicking the arrow next to the check mark.
If you get an error about the naming of the parent folder when trying to open the .ino file, just change the folder name to BalancingWii instead of BalancingWii-master.

**Comment by luxta** [comment]
i get no errors .but my robot doesnt work.hi there
